# Python CircleCI 2.1 configuration file
# for mets-mods2tei
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/python:<< parameters.version >>
    working_directory: ~/repo
    steps:
      - checkout
      - run: pip install -U pip
      - run: make deps deps-test
      - run: make install
      - run: make test
      - run: make coverage
      - codecov/upload
  pypi:
    docker:
      - image: cimg/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: pip install -U pip
      - run: make install
      - run: python setup.py sdist bdist_wheel
      - store_artifacts:
          path: dist/
          destination: artifacts
      - run: |
          pip install -U pip
          pip install twine
          twine upload dist/*

workflows:
  version: 2
  test-all:
    jobs:
      - test:
          matrix:
            parameters:
              version: [3.7.17, 3.8.18, 3.9.18, 3.10.13, 3.11.7]
  deploy:
    jobs:
      - pypi:
          filters:
            branches:
              only: master
